{{- if and (or .Values.providers.gke.autopilot .Values.agents.priorityClassCreate) (not .Values.agents.priorityClassName)}}
apiVersion: scheduling.k8s.io/v1
description: Used for Datadog Agent Components to be scheduled with higher priority.
kind: PriorityClass
metadata:
  name: {{ template "datadog.fullname" . }}
preemptionPolicy: PreemptLowerPriority
value: {{ .Values.agents.priorityClassValue }}
{{- end }}